# Generated by Django 6.0.2 on 2026-02-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('apellido_paterno', models.CharField(blank=True, max_length=250, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('cedula_identidad', models.IntegerField()),
                ('complemento', models.CharField(blank=True, max_length=2, null=True)),
                ('expedicion', models.CharField(choices=[('LP', 'La Paz'), ('SC', 'Santa Cruz'), ('CB', 'Cochabamba'), ('OR', 'Oruro'), ('CH', 'Chuquisaca'), ('BN', 'Beni'), ('PT', 'Potosí'), ('TJ', 'Tarija'), ('PN', 'Pando')], max_length=2)),
                ('grado_instruccion', models.CharField(blank=True, max_length=50, null=True)),
                ('carrera', models.CharField(blank=True, default='NO APLICA', max_length=255, null=True)),
                ('ciudad', models.CharField(max_length=100)),
                ('zona', models.CharField(max_length=100)),
                ('calle_avenida', models.CharField(max_length=100)),
                ('numero_domicilio', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('celular', models.IntegerField()),
                ('cargo_postulacion', models.CharField(max_length=100)),
                ('experiencia_especifica', models.CharField(blank=True, max_length=24, null=True)),
                ('experiencia_general', models.CharField(blank=True, max_length=24, null=True)),
                ('experiencia_procesos_rural', models.CharField(blank=True, max_length=512, null=True)),
                ('es_boliviano', models.BooleanField(default=False)),
                ('registrado_en_padron_electoral', models.BooleanField(default=False)),
                ('ci_vigente', models.BooleanField(default=False)),
                ('disponibilidad_tiempo_completo', models.BooleanField(default=False)),
                ('linea_entel', models.BooleanField(default=False)),
                ('ninguna_militancia_politica', models.BooleanField(default=False)),
                ('sin_conflictos_con_la_institucion', models.BooleanField(default=False)),
                ('sin_sentencia_ejecutoriada', models.BooleanField(default=False)),
                ('cuenta_con_celular_android', models.BooleanField(default=False)),
                ('cuenta_con_powerbank', models.BooleanField(default=False)),
                ('archivo_ci', models.FileField(blank=True, null=True, upload_to='postulantes/ci/')),
                ('archivo_no_militancia', models.FileField(blank=True, null=True, upload_to='postulantes/no_militancia/')),
                ('archivo_hoja_de_vida', models.FileField(blank=True, null=True, upload_to='postulantes/cv/')),
                ('archivo_certificado_ofimatica', models.FileField(blank=True, null=True, upload_to='postulantes/ofimatica/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Postulante',
                'verbose_name_plural': 'Postulantes',
                'db_table': 'postulantes',
            },
        ),
    ]
