# Generated by Django 6.0.2 on 2026-02-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recinto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('departamento', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=200)),
                ('municipio', models.CharField(max_length=200)),
                ('asiento', models.CharField(max_length=200)),
                ('zona', models.CharField(max_length=200)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Recinto',
                'verbose_name_plural': 'Recintos',
                'db_table': 'recintos',
            },
        ),
    ]
