# Generated by Django 6.0.2 on 2026-02-21 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0002_recinto'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulante',
            name='recinto_primera_opcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulantes_primera_opcion', to='postulantes.recinto', verbose_name='Recinto - Primera Opción'),
        ),
        migrations.AddField(
            model_name='postulante',
            name='recinto_segunda_opcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulantes_segunda_opcion', to='postulantes.recinto', verbose_name='Recinto - Segunda Opción'),
        ),
    ]
