# Generated by Django 6.0.2 on 2026-02-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0004_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulante',
            name='cumple_bachiller_o_superior',
            field=models.CharField(choices=[('NO_REVISADO', 'NO REVISADO'), ('CUMPLE', 'CUMPLE'), ('NO_CUMPLE', 'NO CUMPLE')], default='NO_REVISADO', max_length=20, verbose_name='Cumple Bachiller Humanidades o Superior'),
        ),
        migrations.AddField(
            model_name='postulante',
            name='cumple_experiencia_especifica',
            field=models.CharField(choices=[('NO_REVISADO', 'NO REVISADO'), ('CUMPLE', 'CUMPLE'), ('NO_CUMPLE', 'NO CUMPLE')], default='NO_REVISADO', max_length=20, verbose_name='Cumple Experiencia especifica'),
        ),
        migrations.AddField(
            model_name='postulante',
            name='cumple_no_militancia',
            field=models.CharField(choices=[('NO_REVISADO', 'NO REVISADO'), ('CUMPLE', 'CUMPLE'), ('NO_CUMPLE', 'NO CUMPLE')], default='NO_REVISADO', max_length=20, verbose_name='Cumple No militancia'),
        ),
        migrations.AddField(
            model_name='postulante',
            name='observaciones_bachiller_o_superior',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones Bachiller o Superior'),
        ),
        migrations.AddField(
            model_name='postulante',
            name='observaciones_experiencia_especifica',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones Experiencia especifica'),
        ),
        migrations.AddField(
            model_name='postulante',
            name='observaciones_no_militancia',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones No militancia'),
        ),
    ]
