# Generated by Django 6.0.2 on 2026-02-23 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0005_postulante_cumple_bachiller_o_superior_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulante',
            name='cumple_bachiller_o_superior',
        ),
        migrations.RemoveField(
            model_name='postulante',
            name='cumple_experiencia_especifica',
        ),
        migrations.RemoveField(
            model_name='postulante',
            name='cumple_no_militancia',
        ),
        migrations.RemoveField(
            model_name='postulante',
            name='observaciones_bachiller_o_superior',
        ),
        migrations.RemoveField(
            model_name='postulante',
            name='observaciones_experiencia_especifica',
        ),
        migrations.RemoveField(
            model_name='postulante',
            name='observaciones_no_militancia',
        ),
        migrations.CreateModel(
            name='RevisionPostulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_revision', models.DateTimeField(auto_now_add=True)),
                ('cumple_experiencia_especifica', models.CharField(choices=[('NO_REVISADO', 'NO REVISADO'), ('CUMPLE', 'CUMPLE'), ('NO_CUMPLE', 'NO CUMPLE')], default='NO_REVISADO', max_length=20, verbose_name='Cumple Experiencia especifica')),
                ('observaciones_experiencia_especifica', models.TextField(blank=True, null=True, verbose_name='Observaciones Experiencia especifica')),
                ('cumple_no_militancia', models.CharField(choices=[('NO_REVISADO', 'NO REVISADO'), ('CUMPLE', 'CUMPLE'), ('NO_CUMPLE', 'NO CUMPLE')], default='NO_REVISADO', max_length=20, verbose_name='Cumple No militancia')),
                ('observaciones_no_militancia', models.TextField(blank=True, null=True, verbose_name='Observaciones No militancia')),
                ('cumple_bachiller_o_superior', models.CharField(choices=[('NO_REVISADO', 'NO REVISADO'), ('CUMPLE', 'CUMPLE'), ('NO_CUMPLE', 'NO CUMPLE')], default='NO_REVISADO', max_length=20, verbose_name='Cumple Bachiller Humanidades o Superior')),
                ('observaciones_bachiller_o_superior', models.TextField(blank=True, null=True, verbose_name='Observaciones Bachiller o Superior')),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='postulantes.postulante')),
                ('revisado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
            ],
            options={
                'verbose_name': 'Revisión de Postulante',
                'verbose_name_plural': 'Revisiones de Postulantes',
                'ordering': ['-fecha_revision'],
            },
        ),
    ]
