# Generated by Django 6.0.2 on 2026-02-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0006_remove_postulante_cumple_bachiller_o_superior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulante',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observación'),
        ),
    ]
