# Generated by Django 6.0.2 on 2026-02-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0007_add_observacion_to_postulante'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema_activo', models.BooleanField(default=True, verbose_name='Sistema Activo')),
                ('mensaje', models.TextField(default='El sistema de postulación se ha cerrado.', verbose_name='Mensaje de Cierre')),
            ],
            options={
                'verbose_name': 'Configuración de Sistema',
                'verbose_name_plural': 'Configuraciones de Sistema',
            },
        ),
    ]
